### PR TITLE
Checkpoint favoriting

### PR DESCRIPTION
**Pull request by JakeWengroff**

### CODE REVIEW

**Comment by brittanyjspringer** [comment]
@JakeWengroff this has a merge conflict. As an exercise, can you please clone this branch down, fix the conflict, commit it and then merge this PR in. If you need help, please let me know!

**Comment by JakeWengroff** [comment]
Hi, Britt,

I'm confused.  The only way to clone is to clone the entire repository, and
where would I clone that to?  Would I have to create a new or 'shadow'
folder, since I do not want it to interfere with my current, up-to-date
version of Bloccit that I have stored locally in ~/code/bloccit?

So, hypothetically, let's say I create a new 'shadow' or dummy folder,
clone the entire repository which downloads a local version, fix the 2
conflicted files in Sublime, and then push it.  Is that all there is to do?

And because I am in a new shadow/dummy folder, I guess I don't have to
worry about versions of Git, is that right?

Of course, I guess I could just make the changes right in GitHub, no?

Or, I can do git pull from the git master branch, no?

I was thinking about this and I'm just a bit stuck.

Jake

On Wed, May 13, 2015 at 7:13 PM, Brittany Martin notifications@github.com
wrote:

> @JakeWengroff https://github.com/JakeWengroff this has a merge
> conflict. As an exercise, can you please clone this branch down, fix the
> conflict, commit it and then merge this PR in. If you need help, please let
> me know!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JakeWengroff/bloccit-jake/pull/26#issuecomment-101845453
> .

## 

Jake Wengroff
JXB1 Social Business
+1.917.952.6816
j@jxb1.com
http://jxb1.com
Twitter  @JXB1Social

**Comment by JakeWengroff** [comment]
@Brit200313 I responded via email, not sure if you rec'd my message w/ my long list of questions. ;)

**Comment by brittanyjspringer** [comment]
@JakeWengroff Clone was not the right word to use, really. I need you to (please) pull down the branch and fix the merge conflict. If you click on the "use the command line" hyperlink, it tells you what to do. :)

**Comment by JakeWengroff** [comment]
Hi @Brit200313,

Ah, OK.  BTW, I've had this happen several times before -- I haven't told you -- and I usually just use `git pull` to get things back in order.

However, the commands given above here didn't work -- I had to resort to `git pull`.  Everything is clean and up to date -- at least my Command Line says so -- but I still can't do the merge on GitHub.  What now?  Here's what I have:

```
Jakes-Air:bloccit JakeWengroff$ git status
On branch master
Your branch is ahead of 'origin/master' by 3 commits.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
Jakes-Air:bloccit JakeWengroff$ git fetch origin
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 8 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
From github.com:JakeWengroff/bloccit-jake
   3c46d8b..4496f50  master     -> origin/master
   07365fb..528250c  checkpoint-favoriting -> origin/checkpoint-favoriting
Jakes-Air:bloccit JakeWengroff$ git checkout -b checkpoint-favoriting origin/checkpoint-favoriting
fatal: A branch named 'checkpoint-favoriting' already exists.
Jakes-Air:bloccit JakeWengroff$ git merge master
Already up-to-date.
Jakes-Air:bloccit JakeWengroff$ git checkout master
Already on 'master'
Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Jakes-Air:bloccit JakeWengroff$ git merge --no-ff checkpoint-favoriting
Already up-to-date.
Jakes-Air:bloccit JakeWengroff$ git status
On branch master
Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
nothing to commit, working directory clean
Jakes-Air:bloccit JakeWengroff$ git push origin master
To git@github.com:JakeWengroff/bloccit-jake.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:JakeWengroff/bloccit-jake.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Jakes-Air:bloccit JakeWengroff$ git pull
Updating 961f792..4496f50
Fast-forward
Jakes-Air:bloccit JakeWengroff$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
Jakes-Air:bloccit JakeWengroff$ clear

Jakes-Air:bloccit JakeWengroff$ git branch
  assignment-favoriting
  assignment-mocking-with-rspec
  checkpoint-favoriting
  checkpoint-favoriting-2
  checkpoint-mocking-with-rspec
* master
Jakes-Air:bloccit JakeWengroff$ git checkout checkpoint-favoriting
Switched to branch 'checkpoint-favoriting'
Jakes-Air:bloccit JakeWengroff$ git status
On branch checkpoint-favoriting
nothing to commit, working directory clean
Jakes-Air:bloccit JakeWengroff$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
```

**Comment by brittanyjspringer** [comment]
```
~/p/J/bloccit-jake git:master ❯❯❯ git checkout checkpoint-favoriting                                                                                                                                    ✭ ◼
Switched to branch 'checkpoint-favoriting'
Your branch is up-to-date with 'origin/checkpoint-favoriting'.
~/p/J/bloccit-jake git:checkpoint-favoriting ❯❯❯ git merge master                                                                                                                                       ✭ ◼
Auto-merging app/mailers/favorite_mailer.rb
CONFLICT (content): Merge conflict in app/mailers/favorite_mailer.rb
Automatic merge failed; fix conflicts and then commit the result.
~/p/J/bloccit-jake git:checkpoint-favoriting:merge ❯❯❯ subl .                                                                                                                                     ⏎ ✭ ✚ ═ ◼
~/p/J/bloccit-jake git:checkpoint-favoriting:merge ❯❯❯ git status                                                                                                                                   ✭ ✚ ═ ◼
On branch checkpoint-favoriting
Your branch is up-to-date with 'origin/checkpoint-favoriting'.
You have unmerged paths.
  (fix conflicts and run "git commit")

Changes to be committed:

  modified:   app/views/posts/show.html.erb
  modified:   db/schema.rb
  modified:   spec/models/user_spec.rb

Unmerged paths:
  (use "git add <file>..." to mark resolution)

  both modified:   app/mailers/favorite_mailer.rb

Untracked files:
  (use "git add <file>..." to include in what will be committed)

  .ruby-version

~/p/J/bloccit-jake git:checkpoint-favoriting:merge ❯❯❯ git add .                                                                                                                                    ✭ ✚ ═ ◼
~/p/J/bloccit-jake git:checkpoint-favoriting:merge ❯❯❯ git commit -m 'Fixed merge conflict with favorite mailer'                                                                                        ✭ ✚
[checkpoint-favoriting 90586b9] Fixed merge conflict with favorite mailer
~/p/J/bloccit-jake git:checkpoint-favoriting ❯❯❯ git push                                                                                                                                               ⬆ ✭
Username for 'https://github.com': brit200313
Password for 'https://brit200313@github.com':
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 546 bytes | 0 bytes/s, done.
Total 6 (delta 3), reused 0 (delta 0)
```

All fixed up - there was an issue with the favorite mailer :)

**Comment by JakeWengroff** [comment]
Thanks @Brit200313 for doing this......but can we go over this tonight?

I consider myself SO much more adept at Git than I was at the start of the program -- but I can always use more insights. ;)

**Comment by brittanyjspringer** [comment]
Of course!

On Thu, May 14, 2015 at 1:29 PM, Jake Wengroff notifications@github.com
wrote:

> Thanks @Brit200313 https://github.com/Brit200313 for doing
> this......but can we go over this tonight?
> 
> I consider myself SO much more adept at Git than I was at the start of the
> program -- but I can always use more insights. ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JakeWengroff/bloccit-jake/pull/26#issuecomment-102158308
> .

## 

Brittany Martin
about.me/brittany.martin
sfviapgh.com

**Pull request merged**
